root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./cmd/api"
follow_symlink = false
full_bin = ""
send_interrupt = false
stop_on_error = false

exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false

include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []

delay = 1000
kill_delay = 500
log = "build-errors.log"

rerun = false
rerun_delay = 500

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
